INSERT INTO roles(code,name) VALUES ('OWNER','Owner'),('MANAGER','Manager'),('RECEPTIONIST','Receptionist'),('THERAPIST','Therapist'),('ACCOUNTANT','Accountant'),('CUSTOMER','Customer');
INSERT INTO permissions(code,module) VALUES
('BOOKINGS_READ','BOOKINGS'),('BOOKINGS_CREATE','BOOKINGS'),('BOOKINGS_RESCHEDULE','BOOKINGS'),('BOOKINGS_CHECKIN','BOOKINGS'),('BOOKINGS_SERVICE','BOOKINGS'),
('CUSTOMERS_READ','CUSTOMERS'),('CUSTOMERS_WRITE','CUSTOMERS'),('STAFF_READ','STAFF'),('STAFF_WRITE','STAFF'),('SERVICES_READ','SERVICES'),('SERVICES_WRITE','SERVICES'),
('PAYMENTS_READ','PAYMENTS'),('PAYMENTS_RECONCILE','PAYMENTS'),('REPORTS_READ','REPORTS'),('REPORTS_EXPORT','REPORTS'),('ACCOUNTS_MANAGE','ADMINISTRATION'),('RBAC_MANAGE','ADMINISTRATION');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='OWNER';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='MANAGER' AND p.code NOT IN ('RBAC_MANAGE');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='RECEPTIONIST' AND p.code IN ('BOOKINGS_READ','BOOKINGS_CREATE','BOOKINGS_RESCHEDULE','BOOKINGS_CHECKIN','CUSTOMERS_READ','CUSTOMERS_WRITE','PAYMENTS_READ','PAYMENTS_RECONCILE','STAFF_READ','SERVICES_READ');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='THERAPIST' AND p.code IN ('BOOKINGS_READ','BOOKINGS_SERVICE','STAFF_READ','SERVICES_READ');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='ACCOUNTANT' AND p.code IN ('PAYMENTS_READ','PAYMENTS_RECONCILE','REPORTS_READ','REPORTS_EXPORT');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='CUSTOMER' AND p.code IN ('SERVICES_READ','BOOKINGS_CREATE');
