server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lunara_spa?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "placeholder-client-id"
            client-secret: "placeholder-client-secret"
            scope:
              - email
              - profile
